Repository pfplay/pfplay-web, pull requests merged in 2024-07, with the labels that each got.

#133 feat: partyroom chat tab ui
  .gitignore
  .vscode/settings.json
  package.json
  public/icons/Chat/headset_gray.svg
  public/icons/Chat/headset_red.svg
  src/app/_providers/react-query.provider.tsx
  src/app/parties/(room)/[id]/page.tsx
  src/entities/avatar/config/base-size.ts
  src/entities/playlist/lib/playlist-action.context.tsx
  src/entities/playlist/model/playlist-form.model.ts
  src/features/edit-profile-avatar/api/use-update-my-avatar.mutation.ts
  src/features/edit-profile-avatar/ui/done.component.tsx
  src/features/edit-profile-bio/api/use-update-my-bio.mutation.ts
  src/features/edit-profile-bio/model/form.model.ts
  src/features/edit-profile-bio/ui/v1.component.tsx
  src/features/edit-profile-bio/ui/v2-edit.component.tsx
  src/features/partyroom/create/model/form.model.ts
  src/features/playlist/list/ui/collapsable-list.component.tsx
  src/features/sign-out/lib/use-sign-out.hook.ts
  src/shared/api/http/types/@enums.ts
  src/shared/api/http/types/parties.ts
  src/shared/api/websocket/__fixture__/chat-messages.fixture.tsx
  src/shared/api/websocket/types/chat.ts
  src/shared/lib/localization/i18n.context.tsx
  src/shared/ui/components/input/input.component.tsx
  src/shared/ui/components/tab/tab.component.tsx
  src/shared/ui/components/typography/typography.component.tsx
  src/shared/ui/components/typography/typography.stories.tsx
  src/shared/ui/foundation/fonts/galmuri11-Bold.woff2
  src/shared/ui/foundation/fonts/index.ts
  src/widgets/partyroom-chat-panel/index.ts
  src/widgets/partyroom-chat-panel/model/chat-item.model.ts
  src/widgets/partyroom-chat-panel/model/chat-messages.model.tsx
  src/widgets/partyroom-chat-panel/ui/chat-item/authority-headset.component.tsx
  src/widgets/partyroom-chat-panel/ui/chat-item/chat-item.component.tsx
  src/widgets/partyroom-chat-panel/ui/chat-item/chat-message.component.tsx
  src/widgets/partyroom-chat-panel/ui/chat-item/index.ts
  src/widgets/partyroom-chat-panel/ui/partyroom-chat-panel.component.tsx
  src/widgets/sidebar/lib/playlist-action.provider.tsx
Labels: good first issue

#136 refactor(shared/api): Service 객체 클래스화
  src/entities/me/api/use-fetch-me.query.ts
  src/features/edit-profile-avatar/api/use-fetch-avatar-bodies.query.ts
  src/features/edit-profile-avatar/api/use-fetch-avatar-faces.query.ts
  src/features/edit-profile-avatar/api/use-update-my-avatar.mutation.ts
  src/features/edit-profile-bio/api/use-update-my-bio.mutation.ts
  src/features/partyroom/create/ui/form.component.tsx
  src/features/partyroom/list/api/use-fetch-partyrooms.query.ts
  src/features/playlist/add-musics/api/use-add-playlist-music.mutation.ts
  src/features/playlist/add-musics/api/use-search-musics.query.ts
  src/features/playlist/add/api/use-create-playlist.mutation.ts
  src/features/playlist/edit/api/use-update-playlist.mutation.ts
  src/features/playlist/list-musics/api/use-fetch-playlist-musics.query.ts
  src/features/playlist/list/api/use-fetch-playlists.query.ts
  src/features/playlist/remove-musics/api/use-remove-playlist-music.mutation.ts
  src/features/playlist/remove/api/use-remove-playlist.mutation.ts
  src/features/sign-in/by-google/lib/use-sign-in-for-dev.hook.tsx
  src/features/sign-in/by-google/lib/use-sign-in.hook.tsx
  src/features/sign-out/api/use-sign-out.mutation.ts
  src/shared/api/http/client/client.ts
  src/shared/api/http/services/parties.ts
  src/shared/api/http/services/playlists.ts
  src/shared/api/http/services/users.ts
  tsconfig.json
Labels: refactor

#137 fix(shared/api): http service들 this 바인딩 문제 수정
  src/app/_providers/react-query.provider.tsx
  src/shared/api/http/services/parties.ts
  src/shared/api/http/services/playlists.ts
  src/shared/api/http/services/users.ts
Labels: bug

#139 fix(shared/ui/dialog): 중첩 모달 중 제일 상단 모달을 닫을 때 모든 모달이 닫혀버리는 문제
  src/shared/ui/components/dialog/dialog.component.tsx
  src/shared/ui/components/dialog/dialog.stories.tsx
  src/shared/ui/components/dialog/use-dialog.hook.tsx
Labels: bug
